# Generated by Django 4.2.7 on 2024-11-20 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True, help_text="Candidate's election manifesto and goals"),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position_type',
            field=models.CharField(choices=[('faculty', 'Faculty Representative'), ('general', 'General Position')], default='general', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'election')},
        ),
    ]
