# Generated by Django 4.2.7 on 2024-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_options_candidate_manifesto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='election',
            name='manually_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
